engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "client/**.jsx"
exclude_paths: [
  "test",
  "dist",
  "node_modules"
]
