engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: false
  scss-lint:
    enabled: true
exclude_paths: [
  "test",
  "dist",
  "node_modules"
]
